name: Targeted Germline Small-Variant Calling
description: Perform alignment and variant calling with BWA-MEM and DNAscope

selected_requirements_configuration: Exomes
requirements_configurations:
  - name: Panels
    description: Small FASTQ inputs for gene panels
  - name: Exomes
    description: Medium FASTQ inputs for exomes, shallow genomes or large panels
  - name: Genomes
    description: Large FASTQ inputs for high coverage whole genomes

stages:
  - name: Prepare Directories
    description: Prepare output directories
    task_path: tasks/prepare_directories.task.yaml
    depends_on: []

    task_parameters:
      - name: input_folder
        label: Input Folder
        type: directory
        supports_location_mode: 'read_only'

      - name: folder_name
        label: Folder Name
        type: string
        optional: true
        help: "The name of the output folder. If left blank, the name of the input folder will be used."

      - name: base_output_folder
        label: Base Output Folder
        type: directory
        supports_location_mode: 'no_append'
        persist_key: "sentieon.base_output_folder"

  - name: Alignment with BWA-MEM
    description: Align FASTQ files with BWA-MEM
    task_path: tasks/bwa.task.yaml
    depends_on:
      - Prepare Directories

    glob_parameter:
      label: FASTQ Base Folder
      path:
        type: stage
        stage: Prepare Directories
        parameter: input_folder
      glob_ex: '**/*_*.f*q.gz'
      output_parameters:
        - task_parameter_name: input_folder
          expression: '${file_directory}'
        - task_parameter_name: sample_name
          expression: '${2}'
      
    task_parameters:

      - name: output_folder
        label: Output Folder
        type: stage
        stage: Prepare Directories
        stage_parameter_expression: "${output_folder}"

      - name: ml_model
        value: "None"
        label: Machine Learning Model
        type: enum
        choices: [None, Element Biosciences WES 2.1, Element Biosciences WGS 2.1, Illumina WES 2.1, Illumina WGS 2.2,
                  MGI WES 2.1, MGI WGS 2.1, Salus WES 1.0, Salus WGS 1.0, 
                  Ultima Genomics WGS 1.1]
        optional: false
        help: "The Sentieon machine learning model to use for improvements to speed and accuracy for alignment and variant-calling. Leave as None if your data does not match any of the available options. See Sentieon's GitHub page for more information."

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: directory
        supports_location_mode: 'read_only'
        optional: true
        help: "Optionally specify the Sentieon models base path. If not provided, the default models base path will be used. Note that the default models base path must be downloaded and set appropriately. This is only if you select a machine learning model."

      - name: ref_fasta
        label: Reference File (FASTA)
        type: file
        supports_location_mode: 'read_only'
        optional: true
        help: "Optionally specify the reference file to align to. If not provided, the default reference file will be used. Note that the default reference file must be downloaded and set appropriately."

      - name: use_prefix
        label: Use Sample Name as Prefix Filter
        type: stage
        stage_parameter_expression: "true"
        help: "If enabled, only FASTQ files starting with the sample name will be processed. Enable this when the input folder contains FASTQ files from multiple samples. If disabled, all FASTQ files in the input folder are assumed to belong to this sample."


  - name: Variant Calling with DNAscope 
    description: Variant calling from an alignment file with Sentieon's DNAscope algorithm
    task_path: tasks/dnascope.task.yaml
    depends_on:
      - Alignment with BWA-MEM
    
    glob_parameter:
      label: Alignment Folder
      path:
        type: stage
        stage: Prepare Directories
        # This is a parameter expression because output_folder is written to result.evn by prepare_directories
        parameter_expression: "${output_folder}"
      glob_ex: '**/*_*.bam'
      output_parameters:
        - task_parameter_name: input_file
          expression: '${0}'
        - task_parameter_name: sample_name
          expression: '${2}'

    task_parameters:
      - name: output_folder
        label: Output Folder
        type: stage
        stage: Prepare Directories
        stage_parameter_expression: "${output_folder}"

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${model_base_path}"
        optional: true

      - name: ml_model
        label: Machine Learning Model
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ml_model}"
        optional: false

      - name: ref_fasta
        label: Reference File (FASTA)
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ref_fasta}"
      
      - name: output_gvcf
        label: Output GVCF
        type: boolean
        value: "false"
        help: Set to true to output GVCF format instead of VCF. Mutually exclusive with must-call VCF.
